// Chatbot-UI from figma/src/components/TypingIndicator.tsx
import { Avatar, AvatarFallback } from "./ui/avatar";
import { Bot } from "lucide-react";

export function TypingIndicator() {
  return (
    <div className="flex gap-3 p-4 hover:bg-muted/30 transition-colors">
      <Avatar className="size-8 shrink-0">
        <AvatarFallback className="bg-gradient-to-br from-blue-500 to-purple-600 text-white">
          <Bot className="size-4" />
        </AvatarFallback>
      </Avatar>
      
      <div className="flex flex-col gap-1">
        <div className="bg-card text-card-foreground rounded-2xl rounded-bl-md px-4 py-3 shadow-sm border border-border">
          <div className="flex gap-1 items-center">
            <div className="flex gap-1">
              <div className="w-2 h-2 bg-muted-foreground rounded-full animate-bounce [animation-delay:-0.3s]"></div>
              <div className="w-2 h-2 bg-muted-foreground rounded-full animate-bounce [animation-delay:-0.15s]"></div>
              <div className="w-2 h-2 bg-muted-foreground rounded-full animate-bounce"></div>
            </div>
            <span className="text-sm text-muted-foreground ml-2">AI is thinking...</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/routes/chatbot/components/TypingIndicator.svelte
<div class="flex gap-3 p-4 hover:bg-gray-800/30 transition-colors">
	<div class="size-8 shrink-0 rounded-full overflow-hidden">
		<div class="w-full h-full bg-gradient-to-br from-red-500 to-red-600 flex items-center justify-center">
			<svg class="size-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
			</svg>
		</div>
	</div>
	
	<div class="flex flex-col gap-1">
		<div class="bg-gray-800 text-white rounded-2xl rounded-bl-md px-4 py-3 shadow-sm border border-gray-700">
			<div class="flex gap-1 items-center">
				<div class="flex gap-1">
					<div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
					<div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
					<div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
				</div>
				<span class="text-sm text-gray-400 ml-2">AI is thinking...</span>
			</div>
		</div>
	</div>
</div>
