// src/routes/chatbot/components/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import ScrollArea from '$lib/components/ScrollArea.svelte';

	export let isOpen: boolean;
	export let onToggle: () => void;
	export let handleNewChat: () => void;
	export let currentChatId: string;
	export let handleSelectChat: (chatId: string) => void;

	interface Chat {
		id: string;
		title: string;
		timestamp: Date;
	}

	const chats: Chat[] = [
		{ id: "1", title: "Getting started with AI", timestamp: new Date(Date.now() - 1000 * 60 * 30) },
		{ id: "2", title: "React development tips", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2) },
		{ id: "3", title: "Machine learning basics", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24) },
		{ id: "4", title: "Web design principles", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48) },
	];

	const userInfo = {
		name: $page.data.user?.name || "User",
		email: $page.data.user?.email || "user@example.com",
		avatar: $page.data.user?.image || null
	};

	const formatChatTime = (date: Date) => {
		const now = new Date();
		const diffInHours = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60));
		
		if (diffInHours < 1) return "Just now";
		if (diffInHours < 24) return `${diffInHours}h ago`;
		if (diffInHours < 48) return "Yesterday";
		return `${Math.floor(diffInHours / 24)}d ago`;
	};

	let showUserDropdown = false;
	let showChatDropdown: string | null = null;

	const handleClickOutside = (event: MouseEvent) => {
		const target = event.target as HTMLElement;
		if (!target.closest('.dropdown')) {
			showUserDropdown = false;
			showChatDropdown = null;
		}
	};
</script>

<svelte:window on:click={handleClickOutside} />

{#if !isOpen}
	<div class="flex flex-col bg-gray-800 border-r border-gray-700">
		<div class="p-3">
			<button
				on:click={onToggle}
				class="text-gray-400 hover:bg-gray-700 w-full justify-center flex items-center p-2 rounded-lg transition-colors"
				aria-label="Toggle sidebar"
			>
				<svg class="size-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
				</svg>
			</button>
		</div>
		<div class="p-3 pt-0">
			<button
				on:click={handleNewChat}
				class="text-gray-400 hover:bg-gray-700 w-full justify-center flex items-center p-2 rounded-lg transition-colors"
				aria-label="New chat"
			>
				<svg class="size-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
				</svg>
			</button>
		</div>
	</div>
{:else}
	<div class="w-64 bg-gray-800 border-r border-gray-700 flex flex-col">
		<!-- Header -->
		<div class="p-3 border-b border-gray-700">
			<div class="flex items-center justify-between mb-3">
				<h2 class="text-white text-sm font-medium">Conversations</h2>
				<button
					on:click={onToggle}
					class="text-gray-400 hover:text-white hover:bg-gray-700 size-6 p-0 flex items-center justify-center rounded-lg transition-colors"
					aria-label="Close sidebar"
				>
					<svg class="size-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
					</svg>
				</button>
			</div>
			
			<button
				on:click={handleNewChat}
				class="w-full bg-gradient-to-r from-red-500 to-red-600 hover:from-red-600 hover:to-red-700 text-white justify-start gap-2 shadow-lg transition-all duration-200 px-4 py-2 rounded-lg flex items-center"
			>
				<svg class="size-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
				</svg>
				New Chat
			</button>
		</div>

		<!-- Chat List -->
		<ScrollArea class="flex-1">
			<div class="p-2">
				{#each chats as chat}
					<button
						class="group flex items-center gap-2 p-3 rounded-lg mb-2 cursor-pointer transition-all duration-200 w-full text-left {
							currentChatId === chat.id
								? 'bg-gray-700 text-white shadow-sm border border-gray-600/50'
								: 'text-gray-400 hover:bg-gray-700 hover:text-white'
						}"
						on:click={() => handleSelectChat(chat.id)}
					>
						<div class="flex items-center justify-center size-8 rounded-lg transition-colors {
							currentChatId === chat.id ? 'bg-gradient-to-br from-red-500 to-red-600' : 'bg-gray-700'
						}">
							<svg class="size-4 {currentChatId === chat.id ? 'text-white' : 'text-gray-400'}" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
							</svg>
						</div>
						
						<div class="flex-1 min-w-0">
							<p class="truncate text-sm font-medium">{chat.title}</p>
							<p class="text-xs text-gray-400">{formatChatTime(chat.timestamp)}</p>
						</div>
						
						<div class="relative dropdown">
							<div
								on:click={(e) => { e.stopPropagation(); showChatDropdown = showChatDropdown === chat.id ? null : chat.id; }}
								class="opacity-0 group-hover:opacity-100 size-6 p-0 text-gray-400 hover:text-white hover:bg-gray-700/50 flex items-center justify-center rounded-lg transition-all cursor-pointer"
								role="button"
								tabindex="0"
								on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); showChatDropdown = showChatDropdown === chat.id ? null : chat.id; } }}
								aria-label="Chat options"
							>
								<svg class="size-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
								</svg>
							</div>
							
							{#if showChatDropdown === chat.id}
								<div class="absolute right-0 top-full mt-1 w-32 bg-gray-800 border border-gray-600 rounded-lg shadow-lg z-50">
									<button class="w-full text-left px-3 py-2 text-white hover:bg-gray-700 transition-colors rounded-lg text-sm">
										Rename
									</button>
									<button class="w-full text-left px-3 py-2 text-red-400 hover:bg-gray-700 transition-colors rounded-lg text-sm">
										Delete
									</button>
								</div>
							{/if}
						</div>
					</button>
				{/each}
			</div>
		</ScrollArea>

		<!-- User Profile Section -->
		<div class="p-3 border-t border-gray-700">
			<button class="flex items-center gap-3 p-2 rounded-lg hover:bg-gray-700 transition-colors cursor-pointer w-full text-left">
				<div class="size-8 rounded-full overflow-hidden">
					{#if userInfo.avatar}
						<img src={userInfo.avatar} alt={userInfo.name} class="w-full h-full object-cover" />
					{:else}
						<div class="w-full h-full bg-gradient-to-br from-red-500 to-red-600 flex items-center justify-center text-white text-sm font-medium">
							{userInfo.name.split(' ').map((n: string) => n[0]).join('')}
						</div>
					{/if}
				</div>
				
				<div class="flex-1 min-w-0">
					<p class="text-sm font-medium text-white truncate">{userInfo.name}</p>
					<p class="text-xs text-gray-400 truncate">{userInfo.email}</p>
				</div>
				
				<div class="relative dropdown">
					<div
						on:click={() => showUserDropdown = !showUserDropdown}
						class="size-6 p-0 text-gray-400 hover:text-white hover:bg-gray-700/50 flex items-center justify-center rounded-lg transition-colors cursor-pointer"
						role="button"
						tabindex="0"
						on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); showUserDropdown = !showUserDropdown; } }}
						aria-label="User options"
					>
						<svg class="size-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
						</svg>
					</div>
					
					{#if showUserDropdown}
						<div class="absolute right-0 top-full mt-1 w-32 bg-gray-800 border border-gray-600 rounded-lg shadow-lg z-50">
							<button class="w-full text-left px-3 py-2 text-white hover:bg-gray-700 transition-colors rounded-lg text-sm">
								Profile
							</button>
							<button class="w-full text-left px-3 py-2 text-white hover:bg-gray-700 transition-colors rounded-lg text-sm">
								Settings
							</button>
						</div>
					{/if}
				</div>
			</button>
		</div>
	</div>
{/if}

// Chatbot-UI from figma/src/components/Sidebar.tsx
import { useState } from "react";
import { Button } from "./ui/button";
import { ScrollArea } from "./ui/scroll-area";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
import { 
  Plus, 
  MessageSquare, 
  MoreHorizontal, 
  Trash2, 
  Edit3,
  Menu,
  X,
  Settings,
  User
} from "lucide-react";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "./ui/dropdown-menu";

interface Chat {
  id: string;
  title: string;
  timestamp: Date;
}

interface UserInfo {
  name: string;
  email: string;
  avatar?: string;
}

interface SidebarProps {
  isOpen: boolean;
  onToggle: () => void;
  onNewChat: () => void;
  currentChatId?: string;
  onSelectChat?: (chatId: string) => void;
}

export function Sidebar({ isOpen, onToggle, onNewChat, currentChatId, onSelectChat }: SidebarProps) {
  const [chats] = useState<Chat[]>([
    { id: "1", title: "Getting started with AI", timestamp: new Date(Date.now() - 1000 * 60 * 30) },
    { id: "2", title: "React development tips", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2) },
    { id: "3", title: "Machine learning basics", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24) },
    { id: "4", title: "Web design principles", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48) },
  ]);

  const [userInfo] = useState<UserInfo>({
    name: "John Smith",
    email: "john.smith@example.com",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=32&h=32&fit=crop&crop=face&auto=format"
  });

  const formatChatTime = (date: Date) => {
    const now = new Date();
    const diffInHours = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60));
    
    if (diffInHours < 1) return "Just now";
    if (diffInHours < 24) return `${diffInHours}h ago`;
    if (diffInHours < 48) return "Yesterday";
    return `${Math.floor(diffInHours / 24)}d ago`;
  };

  if (!isOpen) {
    return (
      <div className="flex flex-col bg-sidebar border-r border-sidebar-border">
        <div className="p-3">
          <Button
            variant="ghost"
            size="sm"
            onClick={onToggle}
            className="text-sidebar-foreground hover:bg-sidebar-accent w-full justify-center flex items-center"
          >
            <Menu className="size-4" />
          </Button>
        </div>
        <div className="p-3 pt-0">
          <Button
            variant="ghost"
            size="sm"
            onClick={onNewChat}
            className="text-sidebar-foreground hover:bg-sidebar-accent w-full justify-center flex items-center"
          >
            <Plus className="size-4" />
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="w-64 bg-sidebar border-r border-sidebar-border flex flex-col">
      {/* Header */}
      <div className="p-3 border-b border-sidebar-border">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sidebar-foreground text-sm font-medium">Conversations</h2>
          <Button
            variant="ghost"
            size="sm"
            onClick={onToggle}
            className="text-muted-foreground hover:text-sidebar-foreground hover:bg-sidebar-accent size-6 p-0 flex items-center justify-center"
          >
            <X className="size-4" />
          </Button>
        </div>
        
        <Button
          onClick={onNewChat}
          className="w-full bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white justify-start gap-2 shadow-lg transition-all duration-200"
        >
          <Plus className="size-4" />
          New Chat
        </Button>
      </div>

      {/* Chat List */}
      <ScrollArea className="flex-1">
        <div className="p-2">
          {chats.map((chat) => (
            <div
              key={chat.id}
              className={`group flex items-center gap-2 p-3 rounded-lg mb-2 cursor-pointer transition-all duration-200 ${
                currentChatId === chat.id
                  ? 'bg-sidebar-accent text-sidebar-foreground shadow-sm border border-sidebar-border/50'
                  : 'text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-foreground'
              }`}
              onClick={() => onSelectChat?.(chat.id)}
            >
              <div className={`flex items-center justify-center size-8 rounded-lg transition-colors ${
                currentChatId === chat.id ? 'bg-gradient-to-br from-blue-500 to-purple-600' : 'bg-sidebar-accent'
              }`}>
                <MessageSquare className={`size-4 ${currentChatId === chat.id ? 'text-white' : 'text-muted-foreground'}`} />
              </div>
              
              <div className="flex-1 min-w-0">
                <p className="truncate text-sm font-medium">{chat.title}</p>
                <p className="text-xs text-muted-foreground">{formatChatTime(chat.timestamp)}</p>
              </div>
              
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="opacity-0 group-hover:opacity-100 size-6 p-0 text-muted-foreground hover:text-sidebar-foreground hover:bg-sidebar-accent/50 flex items-center justify-center"
                    onClick={(e) => e.stopPropagation()}
                  >
                    <MoreHorizontal className="size-3" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="bg-sidebar border-sidebar-border">
                  <DropdownMenuItem className="text-sidebar-foreground hover:bg-sidebar-accent cursor-pointer">
                    <Edit3 className="size-3 mr-2" />
                    Rename
                  </DropdownMenuItem>
                  <DropdownMenuItem className="text-destructive hover:bg-sidebar-accent cursor-pointer">
                    <Trash2 className="size-3 mr-2" />
                    Delete
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          ))}
        </div>
      </ScrollArea>

      {/* User Profile Section */}
      <div className="p-3 border-t border-sidebar-border">
        <div className="flex items-center gap-3 p-2 rounded-lg hover:bg-sidebar-accent transition-colors cursor-pointer">
          <Avatar className="size-8">
            <AvatarImage src={userInfo.avatar} alt={userInfo.name} />
            <AvatarFallback className="bg-gradient-to-br from-blue-500 to-purple-600 text-white text-sm">
              {userInfo.name.split(' ').map(n => n[0]).join('')}
            </AvatarFallback>
          </Avatar>
          
          <div className="flex-1 min-w-0">
            <p className="text-sm font-medium text-sidebar-foreground truncate">{userInfo.name}</p>
            <p className="text-xs text-muted-foreground truncate">{userInfo.email}</p>
          </div>
          
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="sm"
                className="size-6 p-0 text-muted-foreground hover:text-sidebar-foreground hover:bg-sidebar-accent/50 flex items-center justify-center"
              >
                <MoreHorizontal className="size-3" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="bg-sidebar border-sidebar-border">
              <DropdownMenuItem className="text-sidebar-foreground hover:bg-sidebar-accent cursor-pointer">
                <User className="size-3 mr-2" />
                Profile
              </DropdownMenuItem>
              <DropdownMenuItem className="text-sidebar-foreground hover:bg-sidebar-accent cursor-pointer">
                <Settings className="size-3 mr-2" />
                Settings
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
    </div>
  );
}
